### ISSUE TITLE
Use as a component requires compilation

### ISSUE THREAD

**Issue by jquense** [jaredly/demobox#5]
So when using demobox as a component the consumer (me) needs to remember to compile the demobox module themselves, since `index.js` and `codemirror` both use jsx, and backtick strings. This has proven to be a large pain in the project i'm attempting use demobox in, as i need to make fun exceptions for demobox in my webpack configs.

It would be a lot easier to consume the module if the exported values were already compiled to plain js. There are few patterns i've used in the past to make this really easy, such as developing in `src/` and building plain js files to `lib` before a release. (I've employed said techniques in some of my projects like  [this one](https://github.com/jquense/react-dialogs) if you are interested). The other option of course is just to use es5 and no jsx.

I would have been happier to respond with a PR rather than an issue, but I didn't want to mess with your build flow, and Make is a huge pain to get working on Windows :P. but i'd be happy to help.

many thanks

**Comment by jaredly** [comment]
Ok, I've added a `lib-compiled` directory, so you should be able to `require("demobox/lib-compiled")`, and it will just required the non-jsx/es6 stuff. Also, the css compiled from less can be found in the `/css` directory.

Let me know if that makes things easier.
